version: "3"

services:
    python:
        image: ghcr.io/uekat-studies-zpwjp/uekat-studies-zpwjp-project-python:${PYTHON_IMAGE_TAG}
        platform: linux/x86_64
        ports:
            - ${PYTHON_PORT}:8000
        volumes:
            - app_data:/app:ro
            - .env:/var/www/html/.env:ro
        networks:
            - backend

volumes:
    app_data:

networks:
    backend: