version: "3"

services:
    python:
        build:
            context: .
            args:
                - PYTHON_IMAGE_VERSION=${PYTHON_IMAGE_VERSION}
        platform: linux/x86_64
        working_dir: /app
        ports:
            - ${PYTHON_PORT}:8000
        volumes:
            - .:/app:ro
            - ./data:/var/www/html/data/:rw
            - ./var:/var/www/html/var/:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - backend

networks:
    backend: