name: Build and deploy

on:
    push:
        tags: ["v*.*.*"]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    python-image:
        name: Build and push python image
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            # - name: Set env
            #   run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            # - name: Test
            #   run: |
            #     echo $RELEASE_VERSION
            #     echo ${{ env.RELEASE_VERSION }}

            - name: Load .env file
              uses: xom9ikk/dotenv@v2

            - name: Set env
              run: |
                echo "PYTHON_IMAGE_VERSION=${PYTHON_IMAGE_VERSION}" >> $GITHUB_ENV
                echo "CACHEBUST=$(date +%s)" >> $GITHUB_ENV

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: |
                  ghcr.io/uekat-studies-zpwjp/uekat-studies-zpwjp-project-python
                tags: |
                  type=schedule
                  type=ref,event=branch
                  type=ref,event=pr
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
                  type=sha

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log into registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  build-args: |
                    PYTHON_IMAGE_VERSION=${{ env.PYTHON_IMAGE_VERSION }}
                    CACHEBUST=${{ env.CACHEBUST }}

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: [python-image]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set env
              run: |
                echo "DOCKER_IMAGE_TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/v//g')" >> $GITHUB_ENV

            - name: Upload docker-compose.prod.yml
              uses: appleboy/scp-action@v0.1.4
              with:
                host: ${{ secrets.HOST }}
                port: ${{ secrets.PORT }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                source: "docker-compose.prod.yml"
                target: "${{ secrets.REMOTE_PATH }}"

            - name: Docker compose pull and up
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.HOST }}
                port: ${{ secrets.PORT }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                script: |
                  cd ${{ secrets.REMOTE_PATH }}
                  sed -i "s/^DOCKER_IMAGE_TAG=.*/DOCKER_IMAGE_TAG=${{ env.DOCKER_IMAGE_TAG }}/g" .env
                  docker-compose -f ./docker-compose.prod.yml down -v
                  docker-compose -f ./docker-compose.prod.yml pull
                  docker-compose -f ./docker-compose.prod.yml up -d
